Adding yara scan trigger for PAGE_EXECUTE_READWRITE allocations, useful …
rabbitstack/fibratus pull request #324
Opened 2024-09-14 07:55 UTC by TheAwakener

Adding yara scan trigger for PAGE_EXECUTE_READWRITE allocations, useful when PE image does not contain malicious code, for example, when shellcode is downloaded or decrypted after execution

2024-09-14 10:15 UTC, rabbitstack commented
@TheAwakener thanks for your contribution. I'll get back to your PR shortly.

2024-09-14 10:43 UTC, rabbitstack commented
@TheAwakener General question. If the scan is initiated on every RWX memory allocation event, what are the expected performance penalties? I image we could face a significant event rate and overwhelm the Yara scanner.

2024-09-14 15:51 UTC, TheAwakener commented
@rabbitstack RWX is a rare and suspicious event for memory allocations, for example,  dll images are loaded in a mapped and RX region. If you allocate heap for file reading it's default permission is RW. If you want we can make and additional check for regions unmapped with RWX.

2024-09-14 21:44 UTC, rabbitstack commented
@TheAwakener that sounds good to me. Please, take a look at the other comments. Once they are addressed, the PR should be good to merge.

Bonus request: if you could write a test to cover this new signal, that would be awesome.

2024-09-14 23:24 UTC, TheAwakener commented
@rabbitstack that's would be greater, although I'm new to contributions, can you tell me please where are the other comments to be addressed?

2024-09-15 07:40 UTC, rabbitstack commented
@TheAwakener Go to your PR and scroll down a bit in the Conversation tab. You'll see comments/suggestions I left on individual code lines. Fix them locally, then commit and push.

2024-09-15 15:06 UTC, TheAwakener commented
@rabbitstack ok, maybe I'm missing something but can't see comments on the code:

![Screenshot_20240915-100419](https://github.com/user-attachments/assets/1d832958-540d-405c-9b7b-2a45e4a79b63)

2024-09-15 18:03 UTC, rabbitstack commented
@TheAwakener take a look at the screenshot below. The conversation tab has a badge indicating the interactions on the PR. Lo

![Screenshot_20240915-195724~2](https://github.com/user-attachments/assets/b5e1463b-5fbf-482a-a375-fbf466316a94)
![Screenshot_20240915-195730](https://github.com/user-attachments/assets/03b5d792-2108-4972-a697-77e786d2ac13)

2024-09-15 18:56 UTC, TheAwakener commented
@rabbitstack I already added a commit with the test case for VirtualAlloc with RWX protection flags, although I haven't been able to see the review comments you mention, they simply do not appear in the comments flow:

![image](https://github.com/user-attachments/assets/a2969c6c-9638-4eb1-baef-c96ac1c1fefb)

2024-09-15 19:11 UTC, rabbitstack requested changes

2024-09-15 19:12 UTC, rabbitstack commented
@TheAwakener can you see the comments now?

2024-09-15 19:20 UTC, TheAwakener commented
@rabbitstack yeah, thank you

2024-09-15 19:22 UTC, TheAwakener commented on pkg/yara/scanner.go
> +		err = sn.SetCallback(&matches).ScanProc(int(pid))
We could but we need to use ReadProcess Memory, it is ok?

2024-09-15 19:23 UTC, TheAwakener commented on pkg/yara/scanner.go
> +		}
If we remove this check fubratus crashes because a nil pointer dereference.

2024-09-15 19:34 UTC, rabbitstack commented on pkg/yara/scanner.go
> +		}
It will not if you properly handle the error when accessing the parameter as stated in the previous comment.

2024-09-15 19:36 UTC, rabbitstack commented on pkg/yara/scanner.go
> +		err = sn.SetCallback(&matches).ScanProc(int(pid))
Let's scan the entire process address space for the sake of simplicity/resiliency.

2024-09-15 19:56 UTC, TheAwakener commented on pkg/yara/scanner.go
> +		}
Ok, it is going to be like this:

```
protect, err := evt.Kparams.GetUint32(kparams.MemProtect)
		if err != nil {
			return false, err
		}
```

2024-09-15 19:57 UTC, TheAwakener commented on pkg/yara/scanner.go
> +		if protectVal != windows.PAGE_EXECUTE_READWRITE {
changed

2024-09-15 19:59 UTC, TheAwakener commented on pkg/yara/scanner.go
> +		protectVal, _ := evt.Kparams.GetUint32(kparams.MemProtect)
protect, err := evt.Kparams.GetUint32(kparams.MemProtect)
if err != nil {
	return false, err
}

2024-09-15 20:11 UTC, TheAwakener commented
@rabbitstack new commit pushed with the requested changes

2024-09-15 21:27 UTC, rabbitstack commented
I think the test should be more realistic involving `VirtualAlloc` followed by `WriteProcessMemory` planting a trivial payload to match the rule. But we can leave the improvement for later. I'll merge the PR once mandatory checks pass. Congrats for your first contribution 🎉

2024-09-15 21:31 UTC, TheAwakener commented
@rabbitstack thank you for allow me to participate in this wonderful project

2024-09-15 21:59 UTC, rabbitstack approved these changes

2024-09-15 22:00 UTC, merged